random-xs:
    glass: 
      docker-tag: neurips23-ood-glass
      module: neurips23.ood.glass.glass
      constructor: Glass
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50}]
          query-args: |
            [{"ef":30}, {"ef":50}, {"ef":100}]
text2image-10M:
    glass: 
      docker-tag: neurips23-ood-glass
      module: neurips23.ood.glass.glass
      constructor: Glass
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":8, "L":16}]
          query-args: |
            [{"ef":30}, {"ef":50}, {"ef":100}]

