sparse-small:
    linscancpp:
      docker-tag: neurips23-sparse-linscancpp
      module: neurips23.sparse.linscancpp.linscancpp
      constructor: Linscan
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{}]
          query-args: |
            [{"budget":1},{"budget":0.5},{"budget":0.4},{"budget":0.3},{"budget":0.25},{"budget":0.2},{"budget":0.15},{"budget":0.1},{"budget":0.075},{"budget":0.05}]
sparse-1M:
    linscancpp:
      docker-tag: neurips23-sparse-linscancpp
      module: neurips23.sparse.linscancpp.linscancpp
      constructor: Linscan
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{}]
          query-args: |
            [{"budget":0.5},{"budget":1},{"budget":2},{"budget":4},{"budget":5},{"budget":6},{"budget":7},{"budget":8},{"budget":10}]
sparse-full:
    linscancpp:
      docker-tag: neurips23-sparse-linscancpp
      module: neurips23.sparse.linscancpp.linscancpp
      constructor: Linscan
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"drop_ratio" : 0.15}]
          query-args: |
            [{"budget":0.15}]
          