sparse-small:
    linscancpp:
      docker-tag: neurips23-sparse-linscancpp
      module: neurips23.sparse.linscancpp.linscancpp
      constructor: Linscan
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"drop_ratio" : 0.15}]
          query-args: |
            [{"budget":0.15}]
sparse-1M:
    linscancpp:
      docker-tag: neurips23-sparse-linscancpp
      module: neurips23.sparse.linscancpp.linscancpp
      constructor: Linscan
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"drop_ratio" : 0.0}]
          query-args: |
            [{"budget":0.0}]
sparse-full:
    linscancpp:
      docker-tag: neurips23-sparse-linscancpp
      module: neurips23.sparse.linscancpp.linscancpp
      constructor: Linscan
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"drop_ratio" : 0.10}]
          query-args: |
            [{"budget": 0.10}]
          
